Increase WatchOS deployment target to 3.0
Otherwise attempting to upload a binary to the App Store will result in:
ERROR: ERROR ITMS-90081: "This bundle is invalid. Applications built for
more than one architecture require an iOS Deployment Target of 3.0 or
later."